
public enum Race{
    DWARF_HILL, DWARF_MOUNTAIN, ELF_HIGH, ELF_WOOD, ELF_DARK,
    HALFLING_LIGHTFOOT, HALFLING_STOUT, HUMAN,HUMAN_VARIANT,
    DRAGONBORN, GNOME_FOREST, GNOME_ROCK, HALF_ELF, HALF_ORC,
    TIEFLING

}